#! /usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
from argparse import ArgumentParser

from tool import ChangeType
from tool.new import new_change


def main() -> None:
    parser = ArgumentParser(
        description="""\
            Create a new changelog entry to be staged for the next release. Required \
            values not provided on the command line will be prompted for.""",
    )
    parser.add_argument(
        "-t",
        "--type",
        choices=[t.name.lower() for t in ChangeType],
        help="The type of change being logged.",
    )
    parser.add_argument(
        "-d", "--description", type=str, help="A concise description of the change."
    )
    parser.add_argument(
        "-p",
        "--pull-requests",
        nargs="+",
        help="The pull request that implements the change.",
    )
    parser.add_argument(
        "-r",
        "--repository",
        help="The name of the repository, defaulting to 'smithy-lang/smithy'.",
    )

    args = parser.parse_args()
    new_change(
        change_type=ChangeType[args.type.upper()],
        description=args.description,
        pull_requests=args.pull_requests,
        repository=args.repository,
    )


if __name__ == "__main__":
    main()
