#! /usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
from argparse import ArgumentParser

from tool.release import release
from tool.render import render


def main() -> None:
    parser = ArgumentParser(
        description="""\
            Render the changelog as markdown, optionally including pending features \
            as a new release.""",
    )
    release_group = parser.add_argument_group(
        "release",
        description="""\
            These arguments allow for releasing all pending features in the \
            next-release folder as a new release. If not set, the exisiting releases \
            will be re-rendered.""",
    )
    release_group.add_argument(
        "-v",
        "--release-version",
        type=str,
        help="""\
            The version to use for the staged changelog release. If set, all pending \
            features will be compiled into a release.""",
    )
    release_group.add_argument(
        "-d",
        "--release-date",
        type=str,
        help="""\
            The date of the release in ISO format (e.g. 2024-11-13). If not set, \
            today's date, according to your local time zone, will be used.""",
    )

    args = parser.parse_args()

    if args.release_version:
        release(args.release_version, args.release_date)

    render()


if __name__ == "__main__":
    main()
